orynider_pafiledb_controller:
    path: /pafiledb
    defaults: { _controller: orynider.pafiledb.controller:handle_pafiledb }
orynider_pafiledb_controller_cat:
    path: /category
    defaults: { _controller: orynider.pafiledb.controller.cat:handle_category }
orynider_pafiledb_controller_file:
    path: /file
    defaults: { _controller: orynider.pafiledb.controller.file:handle_file }
orynider_pafiledb_controller_toplist:
    path: /toplist
    defaults: { _controller: orynider.pafiledb.controller.toplist:handle_toplist }
orynider_pafiledb_controller_stats:
    path: /stats
    defaults: { _controller: orynider.pafiledb.controller.stats:handle_stats }
orynider_pafiledb_controller_search:
    path: /search
    defaults: { _controller: orynider.pafiledb.controller.search:handle_search }
orynider_pafiledb_controller_viewall:
    path: /viewall
    defaults: { _controller: orynider.pafiledb.controller.viewall:handle_viewall }
orynider_pafiledb_controller_mcp:
    path: /mcp
    defaults: { _controller: orynider.pafiledb.controller.mcp:handle_mcp }	
orynider_pafiledb_controller_download:
    path: /dload
    defaults: { _controller: orynider.pafiledb.controller.download:handle_download }
orynider_pafiledb_controller_upload:
    path: /upload
    defaults: { _controller: orynider.pafiledb.controller.upload:handle_upload }    