parameters:

    orynider.pafiledb.table.pa_cat: %core.table_prefix%pa_cat
    orynider.pafiledb.table.pa_config: %core.table_prefix%pa_config
    orynider.pafiledb.table.pa_auth_access: %core.table_prefix%pa_auth	
    orynider.pafiledb.table.pa_votes: %core.table_prefix%pa_votes
    orynider.pafiledb.table.pa_license: %core.table_prefix%pa_license
    orynider.pafiledb.table.pa_comments: %core.table_prefix%pa_comments
    orynider.pafiledb.table.pa_custom: %core.table_prefix%pa_custom
    orynider.pafiledb.table.pa_customdata: %core.table_prefix%pa_customdata
    orynider.pafiledb.table.pa_download_info: %core.table_prefix%pa_download_info
    orynider.pafiledb.table.pa_mirrors: %core.table_prefix%pa_mirrors
    orynider.pafiledb.table.pa_files: %core.table_prefix%pa_files	